[versions]
agp = "8.7.3"
circleimageview = "3.1.0"
datamanager = "2.8"
glide = "4.16.0"
appcompat = "1.7.0"
material = "1.12.0"

[libraries]
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
datamanager = { module = "com.github.Jumman04:DataManager", version.ref = "datamanager" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

